// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protos/test.proto

package com.rgtech.bean;

public final class PbTest {
  private PbTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Profile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string nick_name = 1;</code>
     */
    boolean hasNickName();
    /**
     * <code>optional string nick_name = 1;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>optional string nick_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>optional string icon = 2;</code>
     */
    boolean hasIcon();
    /**
     * <code>optional string icon = 2;</code>
     */
    java.lang.String getIcon();
    /**
     * <code>optional string icon = 2;</code>
     */
    com.google.protobuf.ByteString
        getIconBytes();
  }
  /**
   * Protobuf type {@code Profile}
   */
  public static final class Profile extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Profile)
      ProfileOrBuilder {
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Profile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Profile defaultInstance;
    public static Profile getDefaultInstance() {
      return defaultInstance;
    }

    public Profile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Profile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nickName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              icon_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rgtech.bean.PbTest.internal_static_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rgtech.bean.PbTest.Profile.class, com.rgtech.bean.PbTest.Profile.Builder.class);
    }

    public static com.google.protobuf.Parser<Profile> PARSER =
        new com.google.protobuf.AbstractParser<Profile>() {
      public Profile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Profile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NICK_NAME_FIELD_NUMBER = 1;
    private java.lang.Object nickName_;
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 2;
    private java.lang.Object icon_;
    /**
     * <code>optional string icon = 2;</code>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string icon = 2;</code>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string icon = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      nickName_ = "";
      icon_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIconBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIconBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rgtech.bean.PbTest.Profile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Profile)
        com.rgtech.bean.PbTest.ProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rgtech.bean.PbTest.internal_static_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rgtech.bean.PbTest.Profile.class, com.rgtech.bean.PbTest.Profile.Builder.class);
      }

      // Construct using com.rgtech.bean.PbTest.Profile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        icon_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
      }

      public com.rgtech.bean.PbTest.Profile getDefaultInstanceForType() {
        return com.rgtech.bean.PbTest.Profile.getDefaultInstance();
      }

      public com.rgtech.bean.PbTest.Profile build() {
        com.rgtech.bean.PbTest.Profile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rgtech.bean.PbTest.Profile buildPartial() {
        com.rgtech.bean.PbTest.Profile result = new com.rgtech.bean.PbTest.Profile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.icon_ = icon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rgtech.bean.PbTest.Profile) {
          return mergeFrom((com.rgtech.bean.PbTest.Profile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rgtech.bean.PbTest.Profile other) {
        if (other == com.rgtech.bean.PbTest.Profile.getDefaultInstance()) return this;
        if (other.hasNickName()) {
          bitField0_ |= 0x00000001;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasIcon()) {
          bitField0_ |= 0x00000002;
          icon_ = other.icon_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rgtech.bean.PbTest.Profile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rgtech.bean.PbTest.Profile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nickName_ = "";
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object icon_ = "";
      /**
       * <code>optional string icon = 2;</code>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public java.lang.String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icon_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIconBytes() {
        java.lang.Object ref = icon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder setIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder setIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        icon_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Profile)
    }

    static {
      defaultInstance = new Profile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Profile)
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string _string = 1;</code>
     */
    boolean hasString();
    /**
     * <code>optional string _string = 1;</code>
     */
    java.lang.String getString();
    /**
     * <code>optional string _string = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>optional bool _bool = 2;</code>
     */
    boolean hasBool();
    /**
     * <code>optional bool _bool = 2;</code>
     */
    boolean getBool();

    /**
     * <code>optional double _double = 3;</code>
     */
    boolean hasDouble();
    /**
     * <code>optional double _double = 3;</code>
     */
    double getDouble();

    /**
     * <code>optional float _float = 4;</code>
     */
    boolean hasFloat();
    /**
     * <code>optional float _float = 4;</code>
     */
    float getFloat();

    /**
     * <code>optional int32 _int32 = 5;</code>
     */
    boolean hasInt32();
    /**
     * <code>optional int32 _int32 = 5;</code>
     */
    int getInt32();

    /**
     * <code>optional int64 _int64 = 6;</code>
     */
    boolean hasInt64();
    /**
     * <code>optional int64 _int64 = 6;</code>
     */
    long getInt64();

    /**
     * <code>optional uint32 _uint32 = 7;</code>
     */
    boolean hasUint32();
    /**
     * <code>optional uint32 _uint32 = 7;</code>
     */
    int getUint32();

    /**
     * <code>optional uint64 _uint64 = 8;</code>
     */
    boolean hasUint64();
    /**
     * <code>optional uint64 _uint64 = 8;</code>
     */
    long getUint64();

    /**
     * <code>optional sint32 _sint32 = 9;</code>
     */
    boolean hasSint32();
    /**
     * <code>optional sint32 _sint32 = 9;</code>
     */
    int getSint32();

    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    java.util.List<com.rgtech.bean.PbTest.Profile> 
        getProfileList();
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    com.rgtech.bean.PbTest.Profile getProfile(int index);
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    int getProfileCount();
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
        getProfileOrBuilderList();
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              String_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              Bool_ = input.readBool();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              Double_ = input.readDouble();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              Float_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              Int32_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              Int64_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              Uint32_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              Uint64_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              Sint32_ = input.readSInt32();
              break;
            }
            case 106: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                profile_ = new java.util.ArrayList<com.rgtech.bean.PbTest.Profile>();
                mutable_bitField0_ |= 0x00000200;
              }
              profile_.add(input.readMessage(com.rgtech.bean.PbTest.Profile.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          profile_ = java.util.Collections.unmodifiableList(profile_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rgtech.bean.PbTest.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rgtech.bean.PbTest.Person.class, com.rgtech.bean.PbTest.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int _STRING_FIELD_NUMBER = 1;
    private java.lang.Object String_;
    /**
     * <code>optional string _string = 1;</code>
     */
    public boolean hasString() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string _string = 1;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = String_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          String_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string _string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = String_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        String_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int _BOOL_FIELD_NUMBER = 2;
    private boolean Bool_;
    /**
     * <code>optional bool _bool = 2;</code>
     */
    public boolean hasBool() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool _bool = 2;</code>
     */
    public boolean getBool() {
      return Bool_;
    }

    public static final int _DOUBLE_FIELD_NUMBER = 3;
    private double Double_;
    /**
     * <code>optional double _double = 3;</code>
     */
    public boolean hasDouble() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double _double = 3;</code>
     */
    public double getDouble() {
      return Double_;
    }

    public static final int _FLOAT_FIELD_NUMBER = 4;
    private float Float_;
    /**
     * <code>optional float _float = 4;</code>
     */
    public boolean hasFloat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float _float = 4;</code>
     */
    public float getFloat() {
      return Float_;
    }

    public static final int _INT32_FIELD_NUMBER = 5;
    private int Int32_;
    /**
     * <code>optional int32 _int32 = 5;</code>
     */
    public boolean hasInt32() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 _int32 = 5;</code>
     */
    public int getInt32() {
      return Int32_;
    }

    public static final int _INT64_FIELD_NUMBER = 6;
    private long Int64_;
    /**
     * <code>optional int64 _int64 = 6;</code>
     */
    public boolean hasInt64() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 _int64 = 6;</code>
     */
    public long getInt64() {
      return Int64_;
    }

    public static final int _UINT32_FIELD_NUMBER = 7;
    private int Uint32_;
    /**
     * <code>optional uint32 _uint32 = 7;</code>
     */
    public boolean hasUint32() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 _uint32 = 7;</code>
     */
    public int getUint32() {
      return Uint32_;
    }

    public static final int _UINT64_FIELD_NUMBER = 8;
    private long Uint64_;
    /**
     * <code>optional uint64 _uint64 = 8;</code>
     */
    public boolean hasUint64() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 _uint64 = 8;</code>
     */
    public long getUint64() {
      return Uint64_;
    }

    public static final int _SINT32_FIELD_NUMBER = 9;
    private int Sint32_;
    /**
     * <code>optional sint32 _sint32 = 9;</code>
     */
    public boolean hasSint32() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional sint32 _sint32 = 9;</code>
     */
    public int getSint32() {
      return Sint32_;
    }

    public static final int PROFILE_FIELD_NUMBER = 13;
    private java.util.List<com.rgtech.bean.PbTest.Profile> profile_;
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    public java.util.List<com.rgtech.bean.PbTest.Profile> getProfileList() {
      return profile_;
    }
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    public java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
        getProfileOrBuilderList() {
      return profile_;
    }
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    public int getProfileCount() {
      return profile_.size();
    }
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    public com.rgtech.bean.PbTest.Profile getProfile(int index) {
      return profile_.get(index);
    }
    /**
     * <code>repeated .Profile profile = 13;</code>
     */
    public com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
        int index) {
      return profile_.get(index);
    }

    private void initFields() {
      String_ = "";
      Bool_ = false;
      Double_ = 0D;
      Float_ = 0F;
      Int32_ = 0;
      Int64_ = 0L;
      Uint32_ = 0;
      Uint64_ = 0L;
      Sint32_ = 0;
      profile_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStringBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, Bool_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, Double_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, Float_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, Int32_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, Int64_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, Uint32_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, Uint64_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeSInt32(9, Sint32_);
      }
      for (int i = 0; i < profile_.size(); i++) {
        output.writeMessage(13, profile_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStringBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, Bool_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, Double_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, Float_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, Int32_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, Int64_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, Uint32_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, Uint64_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(9, Sint32_);
      }
      for (int i = 0; i < profile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, profile_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rgtech.bean.PbTest.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.rgtech.bean.PbTest.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rgtech.bean.PbTest.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rgtech.bean.PbTest.Person.class, com.rgtech.bean.PbTest.Person.Builder.class);
      }

      // Construct using com.rgtech.bean.PbTest.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProfileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        String_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        Bool_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        Double_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        Float_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        Int32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        Int64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        Uint32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        Uint64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        Sint32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (profileBuilder_ == null) {
          profile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          profileBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
      }

      public com.rgtech.bean.PbTest.Person getDefaultInstanceForType() {
        return com.rgtech.bean.PbTest.Person.getDefaultInstance();
      }

      public com.rgtech.bean.PbTest.Person build() {
        com.rgtech.bean.PbTest.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rgtech.bean.PbTest.Person buildPartial() {
        com.rgtech.bean.PbTest.Person result = new com.rgtech.bean.PbTest.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.String_ = String_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.Bool_ = Bool_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.Double_ = Double_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.Float_ = Float_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.Int32_ = Int32_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.Int64_ = Int64_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.Uint32_ = Uint32_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.Uint64_ = Uint64_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.Sint32_ = Sint32_;
        if (profileBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            profile_ = java.util.Collections.unmodifiableList(profile_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.profile_ = profile_;
        } else {
          result.profile_ = profileBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rgtech.bean.PbTest.Person) {
          return mergeFrom((com.rgtech.bean.PbTest.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rgtech.bean.PbTest.Person other) {
        if (other == com.rgtech.bean.PbTest.Person.getDefaultInstance()) return this;
        if (other.hasString()) {
          bitField0_ |= 0x00000001;
          String_ = other.String_;
          onChanged();
        }
        if (other.hasBool()) {
          setBool(other.getBool());
        }
        if (other.hasDouble()) {
          setDouble(other.getDouble());
        }
        if (other.hasFloat()) {
          setFloat(other.getFloat());
        }
        if (other.hasInt32()) {
          setInt32(other.getInt32());
        }
        if (other.hasInt64()) {
          setInt64(other.getInt64());
        }
        if (other.hasUint32()) {
          setUint32(other.getUint32());
        }
        if (other.hasUint64()) {
          setUint64(other.getUint64());
        }
        if (other.hasSint32()) {
          setSint32(other.getSint32());
        }
        if (profileBuilder_ == null) {
          if (!other.profile_.isEmpty()) {
            if (profile_.isEmpty()) {
              profile_ = other.profile_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureProfileIsMutable();
              profile_.addAll(other.profile_);
            }
            onChanged();
          }
        } else {
          if (!other.profile_.isEmpty()) {
            if (profileBuilder_.isEmpty()) {
              profileBuilder_.dispose();
              profileBuilder_ = null;
              profile_ = other.profile_;
              bitField0_ = (bitField0_ & ~0x00000200);
              profileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProfileFieldBuilder() : null;
            } else {
              profileBuilder_.addAllMessages(other.profile_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rgtech.bean.PbTest.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rgtech.bean.PbTest.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object String_ = "";
      /**
       * <code>optional string _string = 1;</code>
       */
      public boolean hasString() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string _string = 1;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = String_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            String_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string _string = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = String_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          String_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string _string = 1;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        String_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string _string = 1;</code>
       */
      public Builder clearString() {
        bitField0_ = (bitField0_ & ~0x00000001);
        String_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string _string = 1;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        String_ = value;
        onChanged();
        return this;
      }

      private boolean Bool_ ;
      /**
       * <code>optional bool _bool = 2;</code>
       */
      public boolean hasBool() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool _bool = 2;</code>
       */
      public boolean getBool() {
        return Bool_;
      }
      /**
       * <code>optional bool _bool = 2;</code>
       */
      public Builder setBool(boolean value) {
        bitField0_ |= 0x00000002;
        Bool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool _bool = 2;</code>
       */
      public Builder clearBool() {
        bitField0_ = (bitField0_ & ~0x00000002);
        Bool_ = false;
        onChanged();
        return this;
      }

      private double Double_ ;
      /**
       * <code>optional double _double = 3;</code>
       */
      public boolean hasDouble() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double _double = 3;</code>
       */
      public double getDouble() {
        return Double_;
      }
      /**
       * <code>optional double _double = 3;</code>
       */
      public Builder setDouble(double value) {
        bitField0_ |= 0x00000004;
        Double_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double _double = 3;</code>
       */
      public Builder clearDouble() {
        bitField0_ = (bitField0_ & ~0x00000004);
        Double_ = 0D;
        onChanged();
        return this;
      }

      private float Float_ ;
      /**
       * <code>optional float _float = 4;</code>
       */
      public boolean hasFloat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float _float = 4;</code>
       */
      public float getFloat() {
        return Float_;
      }
      /**
       * <code>optional float _float = 4;</code>
       */
      public Builder setFloat(float value) {
        bitField0_ |= 0x00000008;
        Float_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float _float = 4;</code>
       */
      public Builder clearFloat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        Float_ = 0F;
        onChanged();
        return this;
      }

      private int Int32_ ;
      /**
       * <code>optional int32 _int32 = 5;</code>
       */
      public boolean hasInt32() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 _int32 = 5;</code>
       */
      public int getInt32() {
        return Int32_;
      }
      /**
       * <code>optional int32 _int32 = 5;</code>
       */
      public Builder setInt32(int value) {
        bitField0_ |= 0x00000010;
        Int32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 _int32 = 5;</code>
       */
      public Builder clearInt32() {
        bitField0_ = (bitField0_ & ~0x00000010);
        Int32_ = 0;
        onChanged();
        return this;
      }

      private long Int64_ ;
      /**
       * <code>optional int64 _int64 = 6;</code>
       */
      public boolean hasInt64() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 _int64 = 6;</code>
       */
      public long getInt64() {
        return Int64_;
      }
      /**
       * <code>optional int64 _int64 = 6;</code>
       */
      public Builder setInt64(long value) {
        bitField0_ |= 0x00000020;
        Int64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 _int64 = 6;</code>
       */
      public Builder clearInt64() {
        bitField0_ = (bitField0_ & ~0x00000020);
        Int64_ = 0L;
        onChanged();
        return this;
      }

      private int Uint32_ ;
      /**
       * <code>optional uint32 _uint32 = 7;</code>
       */
      public boolean hasUint32() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 _uint32 = 7;</code>
       */
      public int getUint32() {
        return Uint32_;
      }
      /**
       * <code>optional uint32 _uint32 = 7;</code>
       */
      public Builder setUint32(int value) {
        bitField0_ |= 0x00000040;
        Uint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 _uint32 = 7;</code>
       */
      public Builder clearUint32() {
        bitField0_ = (bitField0_ & ~0x00000040);
        Uint32_ = 0;
        onChanged();
        return this;
      }

      private long Uint64_ ;
      /**
       * <code>optional uint64 _uint64 = 8;</code>
       */
      public boolean hasUint64() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 _uint64 = 8;</code>
       */
      public long getUint64() {
        return Uint64_;
      }
      /**
       * <code>optional uint64 _uint64 = 8;</code>
       */
      public Builder setUint64(long value) {
        bitField0_ |= 0x00000080;
        Uint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 _uint64 = 8;</code>
       */
      public Builder clearUint64() {
        bitField0_ = (bitField0_ & ~0x00000080);
        Uint64_ = 0L;
        onChanged();
        return this;
      }

      private int Sint32_ ;
      /**
       * <code>optional sint32 _sint32 = 9;</code>
       */
      public boolean hasSint32() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional sint32 _sint32 = 9;</code>
       */
      public int getSint32() {
        return Sint32_;
      }
      /**
       * <code>optional sint32 _sint32 = 9;</code>
       */
      public Builder setSint32(int value) {
        bitField0_ |= 0x00000100;
        Sint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 _sint32 = 9;</code>
       */
      public Builder clearSint32() {
        bitField0_ = (bitField0_ & ~0x00000100);
        Sint32_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.rgtech.bean.PbTest.Profile> profile_ =
        java.util.Collections.emptyList();
      private void ensureProfileIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          profile_ = new java.util.ArrayList<com.rgtech.bean.PbTest.Profile>(profile_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder> profileBuilder_;

      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public java.util.List<com.rgtech.bean.PbTest.Profile> getProfileList() {
        if (profileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(profile_);
        } else {
          return profileBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public int getProfileCount() {
        if (profileBuilder_ == null) {
          return profile_.size();
        } else {
          return profileBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public com.rgtech.bean.PbTest.Profile getProfile(int index) {
        if (profileBuilder_ == null) {
          return profile_.get(index);
        } else {
          return profileBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder setProfile(
          int index, com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.set(index, value);
          onChanged();
        } else {
          profileBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder setProfile(
          int index, com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.set(index, builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder addProfile(com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.add(value);
          onChanged();
        } else {
          profileBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder addProfile(
          int index, com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.add(index, value);
          onChanged();
        } else {
          profileBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder addProfile(
          com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.add(builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder addProfile(
          int index, com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.add(index, builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder addAllProfile(
          java.lang.Iterable<? extends com.rgtech.bean.PbTest.Profile> values) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, profile_);
          onChanged();
        } else {
          profileBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder clearProfile() {
        if (profileBuilder_ == null) {
          profile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          profileBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public Builder removeProfile(int index) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.remove(index);
          onChanged();
        } else {
          profileBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder getProfileBuilder(
          int index) {
        return getProfileFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
          int index) {
        if (profileBuilder_ == null) {
          return profile_.get(index);  } else {
          return profileBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
           getProfileOrBuilderList() {
        if (profileBuilder_ != null) {
          return profileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(profile_);
        }
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder addProfileBuilder() {
        return getProfileFieldBuilder().addBuilder(
            com.rgtech.bean.PbTest.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder addProfileBuilder(
          int index) {
        return getProfileFieldBuilder().addBuilder(
            index, com.rgtech.bean.PbTest.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .Profile profile = 13;</code>
       */
      public java.util.List<com.rgtech.bean.PbTest.Profile.Builder> 
           getProfileBuilderList() {
        return getProfileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder> 
          getProfileFieldBuilder() {
        if (profileBuilder_ == null) {
          profileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder>(
                  profile_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          profile_ = null;
        }
        return profileBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Profile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Profile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/protos/test.proto\"*\n\007Profile\022" +
      "\021\n\tnick_name\030\001 \001(\t\022\014\n\004icon\030\002 \001(\t\"\267\001\n\006Per" +
      "son\022\017\n\007_string\030\001 \001(\t\022\r\n\005_bool\030\002 \001(\010\022\017\n\007_" +
      "double\030\003 \001(\001\022\016\n\006_float\030\004 \001(\002\022\016\n\006_int32\030\005" +
      " \001(\005\022\016\n\006_int64\030\006 \001(\003\022\017\n\007_uint32\030\007 \001(\r\022\017\n" +
      "\007_uint64\030\010 \001(\004\022\017\n\007_sint32\030\t \001(\021\022\031\n\007profi" +
      "le\030\r \003(\0132\010.ProfileB\031\n\017com.rgtech.beanB\006P" +
      "bTest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Profile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Profile_descriptor,
        new java.lang.String[] { "NickName", "Icon", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "String", "Bool", "Double", "Float", "Int32", "Int64", "Uint32", "Uint64", "Sint32", "Profile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
