// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protos/test.proto

package com.rgtech.bean;

public final class PbTest {
  private PbTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Profile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string nick_name = 1;</code>
     */
    boolean hasNickName();
    /**
     * <code>optional string nick_name = 1;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>optional string nick_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>optional string icon = 2;</code>
     */
    boolean hasIcon();
    /**
     * <code>optional string icon = 2;</code>
     */
    java.lang.String getIcon();
    /**
     * <code>optional string icon = 2;</code>
     */
    com.google.protobuf.ByteString
        getIconBytes();
  }
  /**
   * Protobuf type {@code Profile}
   */
  public static final class Profile extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Profile)
      ProfileOrBuilder {
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Profile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Profile defaultInstance;
    public static Profile getDefaultInstance() {
      return defaultInstance;
    }

    public Profile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Profile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nickName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              icon_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rgtech.bean.PbTest.internal_static_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rgtech.bean.PbTest.Profile.class, com.rgtech.bean.PbTest.Profile.Builder.class);
    }

    public static com.google.protobuf.Parser<Profile> PARSER =
        new com.google.protobuf.AbstractParser<Profile>() {
      public Profile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Profile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NICK_NAME_FIELD_NUMBER = 1;
    private java.lang.Object nickName_;
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nick_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 2;
    private java.lang.Object icon_;
    /**
     * <code>optional string icon = 2;</code>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string icon = 2;</code>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string icon = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      nickName_ = "";
      icon_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIconBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIconBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Profile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rgtech.bean.PbTest.Profile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Profile)
        com.rgtech.bean.PbTest.ProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rgtech.bean.PbTest.internal_static_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rgtech.bean.PbTest.Profile.class, com.rgtech.bean.PbTest.Profile.Builder.class);
      }

      // Construct using com.rgtech.bean.PbTest.Profile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        icon_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rgtech.bean.PbTest.internal_static_Profile_descriptor;
      }

      public com.rgtech.bean.PbTest.Profile getDefaultInstanceForType() {
        return com.rgtech.bean.PbTest.Profile.getDefaultInstance();
      }

      public com.rgtech.bean.PbTest.Profile build() {
        com.rgtech.bean.PbTest.Profile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rgtech.bean.PbTest.Profile buildPartial() {
        com.rgtech.bean.PbTest.Profile result = new com.rgtech.bean.PbTest.Profile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.icon_ = icon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rgtech.bean.PbTest.Profile) {
          return mergeFrom((com.rgtech.bean.PbTest.Profile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rgtech.bean.PbTest.Profile other) {
        if (other == com.rgtech.bean.PbTest.Profile.getDefaultInstance()) return this;
        if (other.hasNickName()) {
          bitField0_ |= 0x00000001;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasIcon()) {
          bitField0_ |= 0x00000002;
          icon_ = other.icon_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rgtech.bean.PbTest.Profile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rgtech.bean.PbTest.Profile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nickName_ = "";
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick_name = 1;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object icon_ = "";
      /**
       * <code>optional string icon = 2;</code>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public java.lang.String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icon_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIconBytes() {
        java.lang.Object ref = icon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder setIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       */
      public Builder setIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        icon_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Profile)
    }

    static {
      defaultInstance = new Profile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Profile)
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2 [default = 0];</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2 [default = 0];</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    int getId();

    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    java.util.List<com.rgtech.bean.PbTest.Profile> 
        getProfileList();
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    com.rgtech.bean.PbTest.Profile getProfile(int index);
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    int getProfileCount();
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
        getProfileOrBuilderList();
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                profile_ = new java.util.ArrayList<com.rgtech.bean.PbTest.Profile>();
                mutable_bitField0_ |= 0x00000008;
              }
              profile_.add(input.readMessage(com.rgtech.bean.PbTest.Profile.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          profile_ = java.util.Collections.unmodifiableList(profile_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rgtech.bean.PbTest.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rgtech.bean.PbTest.Person.class, com.rgtech.bean.PbTest.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1 [default = "HOME"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2 [default = 0];</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2 [default = 0];</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3 [default = "email"];</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILE_FIELD_NUMBER = 6;
    private java.util.List<com.rgtech.bean.PbTest.Profile> profile_;
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    public java.util.List<com.rgtech.bean.PbTest.Profile> getProfileList() {
      return profile_;
    }
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    public java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
        getProfileOrBuilderList() {
      return profile_;
    }
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    public int getProfileCount() {
      return profile_.size();
    }
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    public com.rgtech.bean.PbTest.Profile getProfile(int index) {
      return profile_.get(index);
    }
    /**
     * <code>repeated .Profile profile = 6;</code>
     */
    public com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
        int index) {
      return profile_.get(index);
    }

    private void initFields() {
      name_ = "HOME";
      id_ = 0;
      email_ = "email";
      profile_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < profile_.size(); i++) {
        output.writeMessage(6, profile_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < profile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, profile_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rgtech.bean.PbTest.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rgtech.bean.PbTest.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.rgtech.bean.PbTest.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rgtech.bean.PbTest.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rgtech.bean.PbTest.Person.class, com.rgtech.bean.PbTest.Person.Builder.class);
      }

      // Construct using com.rgtech.bean.PbTest.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProfileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "HOME";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "email";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (profileBuilder_ == null) {
          profile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          profileBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rgtech.bean.PbTest.internal_static_Person_descriptor;
      }

      public com.rgtech.bean.PbTest.Person getDefaultInstanceForType() {
        return com.rgtech.bean.PbTest.Person.getDefaultInstance();
      }

      public com.rgtech.bean.PbTest.Person build() {
        com.rgtech.bean.PbTest.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rgtech.bean.PbTest.Person buildPartial() {
        com.rgtech.bean.PbTest.Person result = new com.rgtech.bean.PbTest.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (profileBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            profile_ = java.util.Collections.unmodifiableList(profile_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.profile_ = profile_;
        } else {
          result.profile_ = profileBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rgtech.bean.PbTest.Person) {
          return mergeFrom((com.rgtech.bean.PbTest.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rgtech.bean.PbTest.Person other) {
        if (other == com.rgtech.bean.PbTest.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (profileBuilder_ == null) {
          if (!other.profile_.isEmpty()) {
            if (profile_.isEmpty()) {
              profile_ = other.profile_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureProfileIsMutable();
              profile_.addAll(other.profile_);
            }
            onChanged();
          }
        } else {
          if (!other.profile_.isEmpty()) {
            if (profileBuilder_.isEmpty()) {
              profileBuilder_.dispose();
              profileBuilder_ = null;
              profile_ = other.profile_;
              bitField0_ = (bitField0_ & ~0x00000008);
              profileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProfileFieldBuilder() : null;
            } else {
              profileBuilder_.addAllMessages(other.profile_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rgtech.bean.PbTest.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rgtech.bean.PbTest.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "HOME";
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1 [default = "HOME"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2 [default = 0];</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2 [default = 0];</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2 [default = 0];</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2 [default = 0];</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "email";
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3 [default = "email"];</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.rgtech.bean.PbTest.Profile> profile_ =
        java.util.Collections.emptyList();
      private void ensureProfileIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          profile_ = new java.util.ArrayList<com.rgtech.bean.PbTest.Profile>(profile_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder> profileBuilder_;

      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public java.util.List<com.rgtech.bean.PbTest.Profile> getProfileList() {
        if (profileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(profile_);
        } else {
          return profileBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public int getProfileCount() {
        if (profileBuilder_ == null) {
          return profile_.size();
        } else {
          return profileBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public com.rgtech.bean.PbTest.Profile getProfile(int index) {
        if (profileBuilder_ == null) {
          return profile_.get(index);
        } else {
          return profileBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder setProfile(
          int index, com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.set(index, value);
          onChanged();
        } else {
          profileBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder setProfile(
          int index, com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.set(index, builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder addProfile(com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.add(value);
          onChanged();
        } else {
          profileBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder addProfile(
          int index, com.rgtech.bean.PbTest.Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfileIsMutable();
          profile_.add(index, value);
          onChanged();
        } else {
          profileBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder addProfile(
          com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.add(builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder addProfile(
          int index, com.rgtech.bean.PbTest.Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.add(index, builderForValue.build());
          onChanged();
        } else {
          profileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder addAllProfile(
          java.lang.Iterable<? extends com.rgtech.bean.PbTest.Profile> values) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, profile_);
          onChanged();
        } else {
          profileBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder clearProfile() {
        if (profileBuilder_ == null) {
          profile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          profileBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public Builder removeProfile(int index) {
        if (profileBuilder_ == null) {
          ensureProfileIsMutable();
          profile_.remove(index);
          onChanged();
        } else {
          profileBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder getProfileBuilder(
          int index) {
        return getProfileFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public com.rgtech.bean.PbTest.ProfileOrBuilder getProfileOrBuilder(
          int index) {
        if (profileBuilder_ == null) {
          return profile_.get(index);  } else {
          return profileBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public java.util.List<? extends com.rgtech.bean.PbTest.ProfileOrBuilder> 
           getProfileOrBuilderList() {
        if (profileBuilder_ != null) {
          return profileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(profile_);
        }
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder addProfileBuilder() {
        return getProfileFieldBuilder().addBuilder(
            com.rgtech.bean.PbTest.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public com.rgtech.bean.PbTest.Profile.Builder addProfileBuilder(
          int index) {
        return getProfileFieldBuilder().addBuilder(
            index, com.rgtech.bean.PbTest.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .Profile profile = 6;</code>
       */
      public java.util.List<com.rgtech.bean.PbTest.Profile.Builder> 
           getProfileBuilderList() {
        return getProfileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder> 
          getProfileFieldBuilder() {
        if (profileBuilder_ == null) {
          profileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.rgtech.bean.PbTest.Profile, com.rgtech.bean.PbTest.Profile.Builder, com.rgtech.bean.PbTest.ProfileOrBuilder>(
                  profile_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          profile_ = null;
        }
        return profileBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Profile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Profile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/protos/test.proto\"*\n\007Profile\022" +
      "\021\n\tnick_name\030\001 \001(\t\022\014\n\004icon\030\002 \001(\t\"\\\n\006Pers" +
      "on\022\022\n\004name\030\001 \002(\t:\004HOME\022\r\n\002id\030\002 \002(\005:\0010\022\024\n" +
      "\005email\030\003 \001(\t:\005email\022\031\n\007profile\030\006 \003(\0132\010.P" +
      "rofileB\031\n\017com.rgtech.beanB\006PbTest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Profile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Profile_descriptor,
        new java.lang.String[] { "NickName", "Icon", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Profile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
